import { useEffect, useState } from "react";
import { supabase } from "../supabase/supabaseClient";
import { Link, useLocation } from "react-router-dom";
import FetchThemes from "../components/fetchThemes";
import SearchBoxWithFilters from "../components/searchBoxWithFilters";
import Spinner from "../components/Spinner";

// The "/products" page: search + theme filter row, then a grid of every
// matching LEGO set. If a theme was clicked (from the home page or the
// theme row here), it filters the grid down to just that theme.
export default function Products() {
  const [legoSets, setLegoSets] = useState([]);
  // True until the current query (all sets, or a theme filter) finishes
  // loading, so we can show a spinner instead of a briefly-empty grid.
  const [loadingSets, setLoadingSets] = useState(true);

  // Gives us access to the current URL, so we can read query params like
  // "?theme=Star%20Wars" from links generated by fetchThemes.jsx.
  const location = useLocation();

  // Extract ?theme=XYZ
  const params = new URLSearchParams(location.search);
  const themeName = params.get("theme"); // null if there's no ?theme= in the URL

  // Load sets - re-runs whenever `themeName` changes (e.g. clicking a
  // different theme button while already on this page).
  useEffect(() => {
    async function loadSets() {
      setLoadingSets(true);
      // Base query: every in-stock set, newest first, with its theme name
      // joined in via the `themes(theme_name)` relationship.
      let query = supabase
        .from("lego_sets")
        .select("*, themes(theme_name)")
        .gt("stock", 0)
        .order("release_year", { ascending: false });

      // If a theme filter is active, look up that theme's id first (the
      // URL only gives us the theme's name, but the lego_sets table is
      // filtered by theme_id), then narrow the query down to it.
      if (themeName) {
        const { data: themeData, error: themeError } = await supabase
          .from("themes")
          .select("theme_id")
          .eq("theme_name", themeName)
          .single();

        if (themeError) {
          console.error("Error fetching theme:", themeError);
        } else if (themeData) {
          query = query.eq("theme_id", themeData.theme_id);
        }
      }

      const { data, error } = await query;
      if (error) {
        console.error("Error fetching sets:", error);
      } else {
        setLegoSets(data);
      }
      setLoadingSets(false);
    }
    loadSets();
  }, [themeName]);

  return (
    <section className="min-h-screen flex flex-col items-center relative">
      {/* Centered Heading + Search */}
      <div
        data-aos="fade-up"
        className="relative z-50 flex flex-col items-center justify-center min-h-[50vh] w-full px-6"
      >
        <div data-aos="fade-right" className="w-full max-w-md ">
          <h1 className="flex justify-center text-3xl font-bold text-black mb-10 text-center border-b-4 border-red-600 relative z-50 ">
            Search Products
          </h1>
          {/* Typing here replaces the grid below with search results,
              same as on the landing page. */}
          <SearchBoxWithFilters onResults={setLegoSets} />
        </div>
      </div>

      {/* Theme Options - clicking one of these navigates back to this same
          page with a different ?theme= in the URL. */}
      <div data-aos="fade-up" className="w-full mb-10 px-6">
        <FetchThemes />
      </div>

      {/* Sets Grid - heading changes depending on whether a theme filter
          is active. */}
      <h2
        data-aos="fade-up"
        className="text-3xl font-bold text-black mb-10 text-center border-b-4 border-red-600 inline-block"
      >
        {themeName ? `${themeName} Sets` : "All LEGO Sets"}
      </h2>
      {loadingSets ? (
        <div className="flex justify-center py-16">
          <Spinner />
        </div>
      ) : (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto px-6">
        {legoSets.map((set, index) => (
          <Link
            key={set.set_id}
            to={`/products/${set.slug}`}
            className="bg-white border border-gray-200 shadow-md rounded-lg p-6
                 hover:shadow-xl hover:scale-105 transform transition"
          >
            {/* Fixed-height image box + object-contain so every product
                photo lines up the same regardless of its original size. */}
            <div
              data-aos="fade-up"
              data-aos-delay={index * 150}
              className="w-full h-56 flex items-center justify-center bg-gray-50 rounded-lg mb-4 overflow-hidden"
            >
              <img
                src={set.image_url}
                alt={set.set_name}
                className="max-w-full max-h-full object-contain"
              />
            </div>
            <h3 className="text-lg font-semibold">{set.set_name}</h3>
            <p className="text-gray-600 mb-2">
              Theme:{" "}
              <span className="font-semibold">{set.themes?.theme_name}</span>
            </p>
            <p className="text-gray-600 mb-2">
              Set Number:{" "}
              <span className="font-semibold">{set.set_number}</span>
            </p>
            <p className="text-gray-600 mb-2">
              Release Year:{" "}
              <span className="font-semibold">{set.release_year}</span>
            </p>
            <p className="text-gray-600 mb-2">
              Stock: <span className="font-semibold">{set.stock}</span>
            </p>
            <p className="text-gray-600 mb-2">
              <span className="text-lg font-semibold text-red-600">
                R{set.price}
              </span>
            </p>
          </Link>
        ))}
      </div>
      )}
    </section>
  );
}
